server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/commerce
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

server.error.include-message: always
logging.file.name: ./logs/commerce-app.log

management:
  endpoints:
    web:
      exposure:
        include: health, info